/**
 * This class is generated by jOOQ
 */
package diamond.jooq.demo.model.jooq.tables.pojos;


import diamond.jooq.demo.model.jooq.tables.interfaces.IArticle;

import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ArticlePojo implements IArticle {

    private static final long serialVersionUID = -1647096328;

    private String    id;
    private String    userId;
    private String    title;
    private String    content;
    private Timestamp createTime;
    private Timestamp updateTime;

    public ArticlePojo() {}

    public ArticlePojo(ArticlePojo value) {
        this.id = value.id;
        this.userId = value.userId;
        this.title = value.title;
        this.content = value.content;
        this.createTime = value.createTime;
        this.updateTime = value.updateTime;
    }

    public ArticlePojo(
        String    id,
        String    userId,
        String    title,
        String    content,
        Timestamp createTime,
        Timestamp updateTime
    ) {
        this.id = id;
        this.userId = userId;
        this.title = title;
        this.content = content;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    @Override
    public String getId() {
        return this.id;
    }

    @Override
    public void setId(String id) {
        this.id = id;
    }

    @Override
    public String getUserId() {
        return this.userId;
    }

    @Override
    public void setUserId(String userId) {
        this.userId = userId;
    }

    @Override
    public String getTitle() {
        return this.title;
    }

    @Override
    public void setTitle(String title) {
        this.title = title;
    }

    @Override
    public String getContent() {
        return this.content;
    }

    @Override
    public void setContent(String content) {
        this.content = content;
    }

    @Override
    public Timestamp getCreateTime() {
        return this.createTime;
    }

    @Override
    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    @Override
    public Timestamp getUpdateTime() {
        return this.updateTime;
    }

    @Override
    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ArticlePojo (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(title);
        sb.append(", ").append(content);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(IArticle from) {
        setId(from.getId());
        setUserId(from.getUserId());
        setTitle(from.getTitle());
        setContent(from.getContent());
        setCreateTime(from.getCreateTime());
        setUpdateTime(from.getUpdateTime());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends IArticle> E into(E into) {
        into.from(this);
        return into;
    }
}
