/**
 * This class is generated by jOOQ
 */
package diamond.jooq.demo.model.jooq.tables.pojos;


import diamond.jooq.demo.model.jooq.tables.interfaces.IUser;

import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserPojo implements IUser {

    private static final long serialVersionUID = 2089615439;

    private String    id;
    private String    username;
    private String    password;
    private String    nickname;
    private String    email;
    private Timestamp birthday;
    private Timestamp createTime;
    private Timestamp loginTime;

    public UserPojo() {}

    public UserPojo(UserPojo value) {
        this.id = value.id;
        this.username = value.username;
        this.password = value.password;
        this.nickname = value.nickname;
        this.email = value.email;
        this.birthday = value.birthday;
        this.createTime = value.createTime;
        this.loginTime = value.loginTime;
    }

    public UserPojo(
        String    id,
        String    username,
        String    password,
        String    nickname,
        String    email,
        Timestamp birthday,
        Timestamp createTime,
        Timestamp loginTime
    ) {
        this.id = id;
        this.username = username;
        this.password = password;
        this.nickname = nickname;
        this.email = email;
        this.birthday = birthday;
        this.createTime = createTime;
        this.loginTime = loginTime;
    }

    @Override
    public String getId() {
        return this.id;
    }

    @Override
    public void setId(String id) {
        this.id = id;
    }

    @Override
    public String getUsername() {
        return this.username;
    }

    @Override
    public void setUsername(String username) {
        this.username = username;
    }

    @Override
    public String getPassword() {
        return this.password;
    }

    @Override
    public void setPassword(String password) {
        this.password = password;
    }

    @Override
    public String getNickname() {
        return this.nickname;
    }

    @Override
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    @Override
    public String getEmail() {
        return this.email;
    }

    @Override
    public void setEmail(String email) {
        this.email = email;
    }

    @Override
    public Timestamp getBirthday() {
        return this.birthday;
    }

    @Override
    public void setBirthday(Timestamp birthday) {
        this.birthday = birthday;
    }

    @Override
    public Timestamp getCreateTime() {
        return this.createTime;
    }

    @Override
    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    @Override
    public Timestamp getLoginTime() {
        return this.loginTime;
    }

    @Override
    public void setLoginTime(Timestamp loginTime) {
        this.loginTime = loginTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserPojo (");

        sb.append(id);
        sb.append(", ").append(username);
        sb.append(", ").append(password);
        sb.append(", ").append(nickname);
        sb.append(", ").append(email);
        sb.append(", ").append(birthday);
        sb.append(", ").append(createTime);
        sb.append(", ").append(loginTime);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(IUser from) {
        setId(from.getId());
        setUsername(from.getUsername());
        setPassword(from.getPassword());
        setNickname(from.getNickname());
        setEmail(from.getEmail());
        setBirthday(from.getBirthday());
        setCreateTime(from.getCreateTime());
        setLoginTime(from.getLoginTime());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends IUser> E into(E into) {
        into.from(this);
        return into;
    }
}
