/**
 * This class is generated by jOOQ
 */
package diamond.jooq.demo.model.jooq;


import diamond.jooq.demo.model.jooq.tables.Article;
import diamond.jooq.demo.model.jooq.tables.User;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in jooq-demo
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>jooq-demo.article</code>.
     */
    public static final Article ARTICLE = diamond.jooq.demo.model.jooq.tables.Article.ARTICLE;

    /**
     * The table <code>jooq-demo.user</code>.
     */
    public static final User USER = diamond.jooq.demo.model.jooq.tables.User.USER;
}
